# https://github.com/khezen/compose-postgres/blob/master/docker-compose.yml
  # Add a new server in PgAdmin:
    # Host name/address postgres
    # Port 5432
    # Username as POSTGRES_USER
    # Password as POSTGRES_PASSWORD

version: '3'
services:
  postgres:
    container_name: bookorg_postgres_container
    image: 'postgres:latest'
    env_file:
      - database.env # configure postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: bookorg_pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - database.env
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge